create table cliente (codigo bigint generated by default as identity, nome varchar(200) not null, primary key (codigo));
create table cliente_limite_credito_risco (codigo_cliente bigint not null, codigo_limite_credito bigint not null, codigo_risco bigint not null, primary key (codigo_cliente, codigo_limite_credito, codigo_risco));
create table limite_credito (codigo bigint generated by default as identity, valor_limite decimal(19,2) not null, primary key (codigo));
create table risco (codigo bigint generated by default as identity, taxa_juros integer, tipo_risco integer not null, primary key (codigo));
alter table cliente add constraint UK_ndm1apkui2hg5y7ds5m48d8ut unique (nome);
alter table risco add constraint UK_ti9e049xhko6imi9p9qurd29q unique (tipo_risco);
alter table cliente_limite_credito_risco add constraint FKgijb5x0nr3869l2h6ur9oiabq foreign key (codigo_cliente) references cliente;
alter table cliente_limite_credito_risco add constraint FKkgf3bt7yuha7006absbyumsnf foreign key (codigo_limite_credito) references limite_credito;
alter table cliente_limite_credito_risco add constraint FK5ti9jg74vwekxexpafroyn7hu foreign key (codigo_risco) references risco;
